JAGUARETE/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SITIO.urls')),
    path('', include("django.contrib.auth.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SITIO/urls.py
from django.urls import path
from . import views

app_name='sitio'
urlpatterns = [
    path('', views.index,name='index'),

    path('categories/<int:id>', views.category,name='categorias'),
    path('categories/', views.category,name='buscar'),

    path('about/',views.aboutus,name="acerca"),
    path('contact/', views.contact,name='contacto'),
    path('new_product/', views.new_product,name='nuevoProducto'),
    path('carrito/',views.carrito,name='carrito'),
    path('register/', views.register,name='register'),

    path('product/', views.product,name='productos'),
    path('product/<int:id>', views.product,name='producto'),
    path('product/edit/<int:id>', views.product_edit,name='productEdit'),
    path('product/delete/<int:id>', views.product_delete,name='productDelete'),

    path('carrito/agregar/<int:id>', views.agregar_producto,name='agregar'),
    path('carrito/eliminar/<int:id>', views.eliminar_producto,name='eliminar'),
    path('carrito/restar/<int:id>', views.restar_producto,name='restar'),
    path('carrito/limpiar/', views.limpiar_carro,name='limpiar'),
    
]

SITIO/models.py
from django.db import models
from django.contrib.auth.models import  User
# Create your models here.

class Categorias(models.Model):
    categoria = models.CharField(max_length=200,null=False, unique=True)
    def __str__(self):
        return f"{self.categoria}"

class Productos(models.Model):
    title=models.CharField(max_length=250, null=False, blank=False)
    image=models.FileField(upload_to='imagenes/', blank=False)
    description=models.CharField(max_length=5000,null=False, blank=False)
    price=models.FloatField(max_length=3,null=False, blank=False)
    categoria_pertenece=models.ForeignKey(Categorias,on_delete=models.CASCADE,null=False, blank=False)

    def __str__(self):
        return '{} {}'.format(self.title , self.categoria_pertenece)

SITIO/forms.py
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from . import models

class RegistrationForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model = User
        fields=('username','email','password1','password2')


class ProductsForm(forms.ModelForm):
    class Meta:
        model= models.Productos
        fields=("title","image","description","price","categoria_pertenece")


SITIO/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.db.models import Q

from . import models
from .forms import RegistrationForm,ProductsForm
from .carro import Carro


# Create your views here.
def index(request):
    context={}
    last_products=models.Productos.objects.order_by('-id')[:3]
    products=models.Productos.objects.all()[:7]
    categories=models.Categorias.objects.all()
    context['last']=last_products
    context['first']=products
    context['Categorias']=categories
    return render(request, 'home.html',context)

def category(request,id=None):
    context={}
    products=models.Productos.objects.filter(categoria_pertenece=id)
    categories=models.Categorias.objects.all()
    context['Categorias']=categories
    if request.method=='POST':
        queryset=request.POST.get("buscar")
        products=models.Productos.objects.filter(Q(title__icontains=queryset)|Q(description__icontains=queryset)).distinct()
        context['buscando']=queryset
        context['posts']=products
        
        return render(request, 'category.html',context)      
    context['products']=products
    context['Cate']=models.Categorias.objects.get(id=id)
    return render(request, 'category.html',context)

def aboutus(request):
    context={}
    categories=models.Categorias.objects.all()
    context['Categorias']=categories
    return render(request,'about.html',context)

def contact(request):
    context={}
    categories=models.Categorias.objects.all()
    context['Categorias']=categories
    return render(request, 'contact.html',context)

def new_product(request):
    context={}
    categories=models.Categorias.objects.all()
    if request.method=='POST':
        form = ProductsForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Producto Creado Exitosamente!")
            return redirect("/")
        else:
            context['form']=form
            return render(request, 'new_product.html',context) 
    else:
        form = ProductsForm()
    context['form']=form    
    context['Categorias']=categories
    return render(request, 'new_product.html',context)

def carrito(request):
    context={}
    categories=models.Categorias.objects.all()
    context['Categorias']=categories
    return render(request,'carrito.html',context)

def register(request):
    context={}
    categories=models.Categorias.objects.all()
    if request.method=="POST":
        form=RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuario Registrado con Exito!!")
        return redirect("/")
    else:
        form=RegistrationForm()
    context['form']=form
    context['Categorias']=categories
    return render(request, 'register.html',context)

def product(request,id=None):
    context={}
    categories=models.Categorias.objects.all()
    if id==None:
        all_products=models.Productos.objects.all()
        context['post']=all_products
    else:
        product=models.Productos.objects.get(id=id)
        context['product']=product
    context['Categorias']=categories
    return render(request, 'product.html',context)

def product_edit(request,id):
    context={}
    product=models.Productos.objects.get(id=id)
    categories=models.Categorias.objects.all()
    if request.method=='GET':
        form=ProductsForm(instance=product)
    else:
        form=ProductsForm(request.POST,request.FILES,instance=product)
        if form.is_valid():
            form.save()
            messages.success(request,f"Se Actualizo con Exito el Producto de nombre:{product.title} - id:{product.id}")
        return redirect('sitio:index')
    context['form']=form
    context['product']=product
    context['Categorias']=categories
    return render(request, 'new_product.html',context)

def product_delete(request,id):
    form=models.Productos.objects.get(id=id)
    if request.method=='POST':
        messages.error(request,f"Se elimino el producto: {form.title}")
        form.delete()
        return redirect("/")

def agregar_producto(request,id):
   
    carro=Carro(request)
    producto=models.Productos.objects.get(id=id)
    carro.agregar(producto=producto)
    return redirect("/carrito")

def eliminar_producto(request,id):
   
    carro=Carro(request)
    producto=models.Productos.objects.get(id=id)
    carro.eliminar(producto=producto)
    return redirect("/carrito")

def restar_producto(request,id):
   
    carro=Carro(request)
    producto=models.Productos.objects.get(id=id)
    carro.restar_producto(producto=producto)
    return redirect("/carrito")

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("/carrito")


SITIO/templates/about.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
Shops
{% endblock title %}


{% block content %}
<div id="about" class=" mx-6">
    <div class="block">
        <div class="tile is-ancestor">
            <div class="tile is-4 is-vertical is-parent ">
                <div class="tile is-parent">
                    <article class="tile is-child notification" >
                      <figure class="image is-4by5">
                        <img src="{% static 'icons/logo.png' %}">
                      </figure>
                    </article>
                </div>
            </div>
            <div class="tile is-parent">
              <div class="tile is-child box">
                <p class="title">Jaguarete KAA S.A</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper diam at erat pulvinar, at pulvinar felis blandit. Vestibulum volutpat tellus diam, consequat gravida libero rhoncus ut. Morbi maximus, leo sit amet vehicula eleifend, nunc dui porta orci, quis semper odio felis ut quam.</p>
                <p>Suspendisse varius ligula in molestie lacinia. Maecenas varius eget ligula a sagittis. Pellentesque interdum, nisl nec interdum maximus, augue diam porttitor lorem, et sollicitudin felis neque sit amet erat. Maecenas imperdiet felis nisi, fringilla luctus felis hendrerit sit amet. Aenean vitae gravida diam, finibus dignissim turpis. Sed eget varius ligula, at volutpat tortor.</p>
                <p>Integer sollicitudin, tortor a mattis commodo, velit urna rhoncus erat, vitae congue lectus dolor consequat libero. Donec leo ligula, maximus et pellentesque sed, gravida a metus. Cras ullamcorper a nunc ac porta. Aliquam ut aliquet lacus, quis faucibus libero. Quisque non semper leo.</p>
              </div>
            </div>
          </div>
</div>
{% endblock content %}

SITIO/templates/carrito.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
About Us
{% endblock title %}


{% block content %}
<div id="about" class=" mx-6">
    <div class="block">
        <div class="tile is-ancestor block is-dark is-outlined">
            <div class="tile is-parent is-justify-content-center is-align-content-center">
                
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title is-size-3 has-text-weight-bold">
                        Bienvenido a tu Carrito <span class="ml-3 is-uppercase">{{ user.username }}</span>
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <div class="table-container">
                                <table class="table is-striped">
                                    <thead class="notification is-info">
                                        <tr>
                                            <th>NOMBRE DEL PRODUCTO</th>
                                            <th>CANTIDAD</th>
                                            <th>PRECIO</th>
                                            <th>ELIMINAR PRODUCTO</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if request.session.carro.items %}
                                        
                                            {% for key,value in request.session.carro.items %}
                                            <tr>
                                                <td class="">{{ value.nombre }}</td>
                                                <td class="">{{ value.cantidad }}</td>
                                                <td class=""> 
                                                    <a href="{% url 'sitio:agregar' value.producto_id %}" class="button is-success">+</a>
                                                    <a href="{% url 'sitio:restar' value.producto_id %}" class="button is-success">-</a><br/>
                                                    ${{ value.precio }}
                                                </td>
                                                <td>
                                                    <a href="{% url 'sitio:eliminar' value.producto_id %}" class="button is-danger is-align-items-center is-justify-content-center">
                                                        <img src="{% static 'icons/delete.svg' %}" alt="" width="30" height="30">
                                                    </a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        
                                        {% else %}
                                            <tr>
                                                <td colspan="4" class="has-text-centered">
                                                    <div class="notification is-danger has-text-weight-bold is-size-3">Sin Productos </div>
                                                </td>
                                            </tr>
                                        {% endif %}
                                    
                                </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <footer class="card-footer box is-fullwidth">
                        <a href="{% url 'sitio:limpiar'%}" class="button is-danger">
                            Vaciar Carrito
                        </a>
                        <a href="{% url 'sitio:index'%}" class="button is-success">
                            Finalizar Compra
                        </a>
                    </footer>
                </div>
                
        </div>
        </div>
    </div>
</div>
{% endblock content %}

SITIO/templates/home.html
{% extends 'layout.html' %}
{% load static %}


{% block Links %}

{% endblock Links %}

{% block title %}
Home
{% endblock title %}





{% block content %}
<div id="home" class=" mx-6">
    
    {% if messages %}
    <div class="block mt-4">

        {% for message in messages %}
            <article class="message is-success">
                <div class="message-header">
                    <p>{{ message }}</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
            </article>
        {% endfor %}

    </div>
    {% endif %}

    <div class="block">
        <div class="tile is-ancestor mt-3">

            {% for product in last %}
                <div class="tile is-parent ">
                    <article class="tile is-child box ">
                        <header class="card-header notification is-warning">
                            <p class="card-header-title is-uppercase is-justify-content-center">
                                {{ product.title }}
                            </p>
                        </header>
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src="{{ product.image.url }}" alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <div style="white-space:wrap; height:120px; overflow-y:hidden;">
                                    {{ product.description|safe }}
                                </div>
                                <br>
                                <span><strong>Precio:</strong></span>
                                <span>$ {{ product.price}}</span>
                            </div>
                        </div> 
                        <footer class="card-footer box is-justify-content-center">
                            {% if user.is_staff %}
                                <a href="{% url 'sitio:productEdit' product.id %}" class="button is-success">
                            {% else %}
                                <a href="{% url 'sitio:producto' product.id %}" class=" button is-success">
                            {% endif %}
                                Ver Producto</a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'sitio:agregar' product.id %}" class=" button is-success">
                                    Agregar al Carro
                                </a>
                            {% endif %}
                        </footer>
                        
                            
                    </article>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="tile is-ancestor block is-dark is-outlined">
        <div class="tile is-parent is-justify-content-center is-align-content-center table-container">
            <table class="table is-striped">
                <thead class="notification is-info">
                    <tr>
                        
                        <th colspan="2">PRODUCTOS</th>
                        <th>CATEGORIA</th>
                        <th>PRECIO</th>
                    </tr>
                    </th>
                <tbody>
                    {% for product in first %}
                    <tr>
                        <td class="">
                            <figure class="image is-64x64">
                                <img src="{{ product.image.url }}" alt="Placeholder image">
                            </figure> 
                        </td>
                        <td class="">
                            {% if user.is_staff %}
                                <a href="{% url 'sitio:productEdit' product.id %}">
                            {% else %}
                                <a href="{% url 'sitio:producto' product.id %}">
                            {% endif %}
                                    {{ product.title }}
                                </a>
                        </td>
                        <td class=""> {{ product.categoria_pertenece }} </td>
                        <td class=""> ${{ product.price }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

SITIO/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    {% block Links %} {% endblock Links %}
    {% load static %}

</head>

<body>
    <header  class="m-1" >
        <div class="pt-2 ml-4" style="position:absolute; top:0px; left:0px">
            <img src="{% static 'icons/logo.png' %}" alt="categories img" width="35px" height="35px"/>
        </div>
        <div class="is-size-1-desktop is-size-1-tablet is-size-1-touch is-hidden-mobile is-uppercase  has-text-weight-bold has-text-black" style="position:absolute; top:-5px; left:5%">
            JAGUARETE KAA S.A
        </div>
        <nav class="breadcrumb has-dot-separator is-right mr-2 pt-2" aria-label="breadcrumbs">
            <ul>
                {% if user.is_authenticated %} 
                        <li>
                            <a id="carrito" href="{% url 'sitio:carrito' %}" class="button is-primary">
                                <img src="{% static 'icons/carrito.svg' %}" alt="shops img" width="25px" height="25px"
                                    style="padding-right: 0.2rem;" /><strong>Carrito</strong>
                            </a>
                        </li>
                        <li>
                            <a id="logout" href="{% url 'logout' %}" class="button is-danger is-outlined">
                                <strong>Log out</strong><img src="{% static 'icons/logout.svg' %}" alt="log out img"
                                    width="25px" height="25px" style="padding-left: 0.2rem;" />
                            </a>
                        </li>
                {% else %}
                    <li>
                        <a id="register" class="button is-primary" href="{% url 'sitio:register' %}">
                            <img src="{% static 'icons/register.svg' %}" alt="add user img" width="25px" height="25px"
                                style="padding-right: 0.2rem;" /><strong>Registrarse</strong>
                        </a>
                    </li>
                    <li>
                        <a id="login" href="{% url 'login' %}" class="button is-link is-outlined">
                            <img src="{% static 'icons/login.svg' %}" alt="log in img" width="25px" height="25px"
                                style="padding-right: 0.2rem;" /><strong>Log in</strong>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <nav class="navbar is-info" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a role="button" id="burguer" class="navbar-burger" aria-label="menu" aria-expanded="false"
                    data-target="encabezado">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
    
            <div id="encabezado" class="navbar-menu">
                <div class="navbar-start">
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="navbar-item has-text-black " href="{% url 'sitio:index' %}"><img
                                    src="{% static 'icons/home.svg' %}" alt="home img" width="22px" height="22px"
                                    style="padding-right: 0.2rem;" /> HOME </a>
    
                            <a class="navbar-item has-text-black " href="{% url 'sitio:acerca' %}"><img
                                    src="{% static 'icons/about.svg' %}" alt="about img" width="22px" height="22px"
                                    style="padding-right: 0.2rem;" /> ACERCA DE </a>
                            <a class="navbar-item has-text-black " href="{% url 'sitio:contacto' %}"><img
                                    src="{% static 'icons/contact.svg' %}" alt="contact img" width="22px" height="22px"
                                    style="padding-right: 0.2rem;" /> CONTACTO </a>
                            {% if user.is_staff %}
                                <a class="navbar-item has-text-black " href="{% url 'sitio:nuevoProducto' %}"><img
                                        src="{% static 'icons/new.svg' %}" alt="newProduct img" width="22px" height="22px"
                                        style="padding-right: 0.2rem;" /> NUEVO PRODUCTO </a>
                                <a class="navbar-item has-text-black " href="{% url 'sitio:productos'  %}"><img
                                        src="{% static 'icons/new.svg' %}" alt="newProduct img" width="22px" height="22px"
                                        style="padding-right: 0.2rem;" /> PRODUCTOS </a>
                            {% endif %}
                            <div class="navbar-item has-dropdown is-hoverable">
                                <a class="navbar-link ">
                                    <span class="has-text-black"><img src="{% static 'icons/categories.svg' %}" alt="categories img"
                                            width="22px" height="22px"
                                            style="padding-right: 0.2rem; " />CATEGORIAS</span>
                                </a>
                                <div class="navbar-dropdown">
                                    {% for categoria in Categorias %}
                                        <a class="navbar-item" href="{% url 'sitio:categorias' categoria.id %}">{{categoria.categoria}}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="navbar-end">
                    <div class=" navbar-item">
                        <form action="{% url 'sitio:buscar' %}" method="POST" class="field has-addons">
                            {% csrf_token %}
                            <div class="control ">
                                <input class="input is-dark is-rounded" type="text" placeholder="Buscar..." name="buscar">
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-dark">
                                    Buscar
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="px-2" id="tab-content">
            {% block content %}

            {% endblock content %}
        </div>
    </main>
    <footer class="footer my-5 py-5">
        <div class="content has-text-centered">
            <p>Jaguarete KAA S.A Copyright 2021, Todos los derechos reservados.</p>
            <p>Deseñado Por Henry Sebastian Eraso Lasso</p>
        </div>
    </footer>
    <script src="{% static 'js/index.js' %}" type="module"></script>`

    {% block scripts %}

    {% endblock scripts %}

</body>

</html>

SITIO/templates/product.html
{% extends 'layout.html' %}
{% load static %}


{% block Links %}

{% endblock Links %}

{% block title %}
Product
{% endblock title %}
    

{% block content %}
<div id="product" class=" mx-6">
    
    {% if user.is_staff %}
        <div class="tile is-ancestor block is-dark is-outlined">
            <div class="tile is-parent is-justify-content-center is-align-content-center table-container">
                    <table class="table is-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>TITLE</th>
                                <th>CATEGORIA</th>
                                <th>PRECIO</th>
                                <th>EDITAR</th>
                            </tr>
                        </th>
                        <tbody>
                            {% for product in post %}
                            <tr>
                                <td class="">{{ product.id }} </td>
                                <td class=""> {{ product.title }} </td>
                                <td class=""> {{ product.categoria_pertenece }} </td>
                                <td class=""> ${{ product.price }}</td>
                                <td><button><a href="{% url 'sitio:productEdit' product.id %}">Editar</a></button></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>
    {% else %}
        <div class="block">
            <div class="tile is-ancestor">
                <div class="tile is-parent">
                    <article class="tile is-child box">
                        <header class="card-header">
                            <p class="card-header-title is-uppercase is-justify-content-center">
                                {{ product.title }} <span class="ml-2 tag is-warning">{{ product.categoria_pertenece }}</span>
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="columns">
                                <div class="column">
                                    <div class="card-image box ">
                                        <figure class="image is-4by5">
                                            <img src="{{ product.image.url }}" alt="Placeholder image">
                                        </figure>
                                    </div>
                                </div>
                                <div class="column">
                                    <div class="">
                                        <span class="is-size-3 has-text-weight-bold">Descripcion del Producto:</span>
                                    </div>
                                    <div class="content">
                                        {{ product.description|safe }}
                                        <br>
                                        <div class="is-flex is-align-items-center is-justify-content-center">
                                            <span class="is-size-3 has-text-weight-bold">Precio: <span class="has-text-success">$ {{ product.price }}</span></span>
                                        </div>
                                    </div>
                                </div> 
                            </div> 
                        </div>
                        {% if user.is_authenticated %}
                            <footer class="card-footer box is-justify-content-center">
                                {% if user.is_staff %}
                                    <a href="{% url 'sitio:productEdit' product.id %}" class="button is-success">
                                        Ver Producto
                                    </a>
                                {% endif %}
                                <a href="{% url 'sitio:agregar' product.id %}" class=" button is-success">
                                    Agregar al Carro
                                </a>
                            </footer>
                        {% endif %}
                    </article>
                </div>
            </div>
        </div>
    {% endif %}
        
</div>
{% endblock content %}